FROM nvcr.io/nvidia/tensorflow:21.12-tf2-py3
# ENV OPID=1000

# RUN echo $OPID is running
# RUN groupadd -g $OPID opr
# RUN useradd -rm -d /home/opr -s /bin/bash -u ${OPID} -g ${OPID} -p "opr1234" opr
# RUN usermod -aG sudo opr

RUN apt-get update \
    && apt-get -y install sudo && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# USER opr
# WORKDIR /home/opr

RUN pip3 install --upgrade pip

RUN pip3 install torch python-dotenv  matplotlib \
 sklearn scipy arch==5.0.1 plotly cufflinks \
 keras==2.7.0 tensorflow==2.7.0 keras-tuner==1.1.0 \
 ta==0.7.0 seaborn==0.11.2 \
 pandas==1.3.3 numpy==1.19.5 statsmodels==0.13.0 \
 SQLAlchemy==1.4.46 pymysql==1.0.2 \
 eoddata-client==0.3.3 tiingo yfinance \
 spyder-kernels sshtunnel==0.4.0

RUN pip3 install jupyter jupyterlab

RUN export PATH=$PATH:~/.local/bin