version: "1"

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8.1-debian-11-r41'
    container_name: myzook_1
    ports:
      - '2181:2181'
    volumes:
      - ./zookeeper-data:/bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.4.0-debian-11-r37
    container_name: mykafka_1
    ports:
      - "9092:9092"
    volumes:
      - ./kafka-data:/bitnami/kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    depends_on: 
      - zookeeper

